# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy static web app to Azure Web App - tomasseguroWebApp

on:
  push:
    branches:
      - app
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Deploy static web content to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tomasseguroWebApp'
          slot-name: 'Production'
          package: './app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8A961A0D66A346C4A309DCFBA030ADDA }}